### PR TITLE
Executor key change lead to possible null reference exception

### PR DESCRIPTION
**Pull request by patheems**
enhancement of #695

### CODE REVIEW

**Comment by yang-xiaodong** [comment]
Hello @patheems , There seems has a conflicts that need to resolved

**Review by yang-xiaodong — APPROVED** [review]
LGTM

**Comment by patheems** [comment]
Hi @yang-xiaodong,

Could you make a Preview build of this merge so I can use that package? 

Thx!

**Comment by yang-xiaodong** [comment]
Hi,  `3.1.2-preview-120665033` is released to NuGet

**Pull request merged**
