### PR TITLE
Fix : different methodInfo but get same executor

### PR DESCRIPTION
**Pull request by yrinleung**
Fix : different methodInfo but get same executor

### CODE REVIEW

**Comment by yang-xiaodong** [comment]
Hello, Thanks for your PR.

Please describe the scene and example of MetadataToken for methodInfo with the same values?

According to the explanation of MSDN:

https://docs.microsoft.com/en-us/dotnet/api/system.reflection.memberinfo.metadatatoken?view=netcore-3.1#System_Reflection_MemberInfo_MetadataToken

> MetadataToken
> A value which, in combination with Module, uniquely identifies a metadata element.

**Comment by yrinleung** [comment]
```
    public interface IIntegrationEventHandler<TIntegrationEvent> 
    {
        Task Handle(TIntegrationEvent @event);
    }
    public class TestIntegrationEvent
    {
    }
    public class Test1IntegrationEvent
    {
    }


    var metadataToken = typeof(IIntegrationEventHandler<TestIntegrationEvent>).MetadataToken;
    var metadataToken1 = typeof(IIntegrationEventHandler<Test1IntegrationEvent>).MetadataToken;

    var bl = metadataToken == metadataToken1;
    Console.WriteLine($"metadataToken:{metadataToken}");
    Console.WriteLine($"metadataToken1:{metadataToken1}");
    Console.WriteLine($"bl:{bl}");
```
Result:
image

**Comment by yrinleung** [comment]
scene:
> In the project, I rewrite “ConsumerServiceSelector"  to read “IIntegrationEventHandler&#60;TIntegrationEvent&#62;" convert "ConsumerExecutorDescriptor” ,so "metadatatoken" is the same

**Comment by yang-xiaodong** [comment]
You're using the same object to printing the value

**Comment by yrinleung** [comment]
Yes, but the subscription in the old project is based on generic subscription, so only be compatible
```
public interface IEventBus
{
        void Subscribe<T, TH>()
            where T : IIntegrationEvent
            where TH : IIntegrationEventHandler<T>;
}
```
In the current project, I rewrite "ISubscribeInvoker" to compatible

**Comment by yang-xiaodong** [comment]
Hello, we don't think this is a bug that needs to be fixed or improved.

GetHashCode does not guarantee that different objects will return unique values.

You can implement ISubscribeInvoker to customize yours behavior

**Comment by yang-xiaodong** [comment]
Hello, we don't think this is a bug that needs to be fixed or improved.

GetHashCode does not guarantee that different objects will return unique values.

You can implement ISubscribeInvoker to customize yours behavior

**Comment by yrinleung** [comment]
OK , thank you

**Pull request closed without merging**
