### PR TITLE
test custom serializer, pls review my code

### PR DESCRIPTION
**Pull request by QuanJingHong**

### CODE REVIEW

**Comment by yang-xiaodong** [comment]
你好，我在这个PR中看到了大量更改，但是我无法找到这个PR中所做的突出工作，你能进行一些描述吗？

1、此PR的背景和动机
2、设计方案/方法
3、目前的改动对我们的影响

Hello, I have seen a lot of changes in this PR, but I cannot find the outstanding work done in this PR. Can you describe it in detail?

1. The background and motivation
2. Design plan/method
3. The impact of the current changes

**Comment by Guan9hong** [comment]
The background and motivation:
I working with geometry data, I can using Newtonsoft or Build-it serialization to serialize the data.

Design plan/method:

So I want to implement a method to deal with it.
I create a class called SerializerRegistry, It make a mapping with Type and Serializer. When I pass a Type it return a Serializer instance.

**Comment by yang-xiaodong** [comment]
你好，我们暂时可能无法合并此PR，我们需要长时间的评估，因为涉及到大量改动。

**Comment by Guan9hong** [comment]
pls review my solution

**Comment by yang-xiaodong** [comment]
Hello, after discussion, due to the PR changes a lot of design have not been accepted, thanks

**Pull request closed without merging**
