### PR TITLE
Update Kafka to 1.8.2

### PR DESCRIPTION
**Pull request by deeja**

### CODE REVIEW

**Comment by xiangxiren** [comment]
Why need to upgrade?

**Comment by deeja** [comment]
We are using 1.8.2 as there are some essential updates since 1.6.2 (February) 
https://github.com/confluentinc/confluent-kafka-dotnet/releases
https://github.com/edenhill/librdkafka/releases/tag/v1.8.2

**Comment by deeja** [comment]
We are also using the Confluent Schema registry https://www.nuget.org/packages/Confluent.SchemaRegistry/

**Comment by xiangxiren** [comment]
You can add a reference to version 1.8.2 separately in the project.

**Pull request closed without merging**
