### PR TITLE
Add MQTT Extensions Support

### PR DESCRIPTION
**Pull request by jinzaz**
你好，我尝试了进行CAP支持对于MQTT的扩展支持，不知道是否有改支持的需要，提交了一个pul reuqest，期待回复

### CODE REVIEW

**Comment by yang-xiaodong** [comment]
Would you like to support as a community extension? We will add your repository to our documentation

https://cap.dotnetcore.xyz/user-guide/zh/transport/general/#_4

**Comment by jinzaz** [comment]
@yang-xiaodong  I think so. Do I need to create and name an extended warehouse separately?, such as CAP.Extensions.MQTT

**Comment by yang-xiaodong** [comment]
Yes, you can create a repository just named `Jinzaz.CAP.MQTT` in your account,

I recommend you to use the CAP 7.0-preview version as reference, which is our next major release in the near future.

Also, you can create a PR to us about modify the docs and add your repository link to 
https://github.com/dotnetcore/CAP/blob/master/docs/content/user-guide/zh/transport/general.md

Thanks for your contribute!

**Comment by jinzaz** [comment]
Ok,i knowed!

**Pull request closed without merging**
