### PR TITLE
Updated AzureServiceBus

### PR DESCRIPTION
**Pull request by giorgilekveishvili-meama**
Added option for custom SQL Filters on topic subscribtion

### CODE REVIEW

**Comment by giorgilekveishvili-meama** [comment]
@mviegas Can you review please?

**Review by mviegas — CHANGES_REQUESTED** [review]
Looks good @giorgilekveishvili-meama ! Would you mind adding a sample for it, for better documentation and a leaner learning curve purpose?

Thank you!

**Comment by giorgilekveishvili-meama** [comment]
I have updated documentation , please check @mviegas

**Comment by mviegas** [comment]
Thanks for the doc update @giorgilekveishvili-meama ! If you could add this in the samples as well, we can merge this. 🙏

**Comment by giorgilekveishvili-meama** [comment]
I have added SQLFIlter in Sample @mviegas

**Review by mviegas — APPROVED** [review]
Good to go, thanks!

**Pull request merged**
